@startuml

(*) --> "User Rest Request"

--> === lb ===
note right: Traditional HTTP Load Balancer

=== lb === --> "Spray.IO" as s1
=== lb === --> "Spray.IO" as s2
=== lb === --> "Spray.IO" as s3

s1 --> "Service" as sv1
s1 --> "Service" as sv2
s1 --> "Service" as sv3
s1 --> "Service" as sv4
s1 --> "Service" as sv5
s1 --> "Service" as sv6

s2 --> sv1
s2 --> sv2
s2 --> sv3
s2 --> sv4
s2 --> sv5
s2 --> sv6

s3 --> sv1
s3 --> sv2
s3 --> sv3
s3 --> sv4
s3 --> sv5
s3 --> sv6

@enduml