@startuml

cloud "Cluster" {

	node "Service 1" {
	  [Service Logic] as logic1
	  [Message Module] as message1
	}
	
	node "Service 2" {
	  [Message Module] as message2
	  [Service Logic] as logic2
	}

  [Service Registry]
}

logic1 <-down-> message1
logic2 <-down-> message2

message1 <-left-> [Service Registry] : 1) Check Address for Service 2

message1 <-left-> message2 : 2) Send Message

@enduml