@startuml

package "Docker Repository" {

  object SomeServiceDocker {
    - Install application services
    - Configure service container
    - Start service container
  }


  object ServiceContainerDocker {
    - Install service container
  }

  object JavaDocker {
    - Install java JDK
  }

  object UbuntuDocker {
    - Install Ubuntu (Using Shared CoreOS Kernel)
  }
}


SomeServiceDocker --|> ServiceContainerDocker
ServiceContainerDocker --|> JavaDocker
JavaDocker --|> UbuntuDocker


note as n
  This is one way to deploy a service directly through docker images.
  The other is to use the SMScheduler to push the service to a running container
end note

n -left-> SomeServiceDocker

@enduml