@startuml

[*] --> Service

state Service {
	CommandHandler --> MetricClient
	Component --> MetricClient
	MetricClient --> CodaHale
	
	
	Component : Any Code
	CommandHandler : Auto Exposes Key Metrics
	MetricClient : Edifecs Monitoring API
	CodaHale : Batches and Sends Metric Information 
}


CodaHale --> JMXReporter #CCCCCC
CodaHale --> GraphiteReporter #CCCCCC
CodaHale --> EdifecsMetricReporter
CodaHale --> ZabbixReporter #CCCCCC
CodaHale --> CSV #CCCCCC

JMXReporter --> JVisualVM #CCCCCC
GraphiteReporter --> Graphite #CCCCCC
ZabbixReporter --> Zabbix #CCCCCC

EdifecsMetricReporter : Central Collection of Metric Data

@enduml